# Generated by Django 2.0.2 on 2018-02-24 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=150)),
                ('college_type', models.CharField(choices=[('choose', 'CHOOSE'), ('autonomous', 'autonomous'), ('annauniversity', 'annauniversity')], default='choose', max_length=150)),
                ('college_date', models.DateField()),
                ('college_time', models.TimeField()),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('pin_code', models.IntegerField()),
                ('placement_staff_name', models.CharField(max_length=150)),
                ('ph_number', models.IntegerField()),
                ('mailid', models.EmailField(max_length=254)),
                ('ave_count', models.IntegerField()),
                ('remeet', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
