# Generated by Django 2.0.2 on 2018-02-26 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('company_type', models.CharField(choices=[('choose', 'CHOOSE'), ('product', 'PRODUCT'), ('service', 'SERVICE')], default='choose', max_length=150)),
                ('company_date', models.DateField()),
                ('company_time', models.TimeField()),
                ('door_no', models.CharField(max_length=150)),
                ('street1', models.CharField(max_length=150)),
                ('street2', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('pin_code', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('ph_number', models.IntegerField()),
                ('mailid', models.EmailField(max_length=254)),
                ('job_description', models.TextField()),
                ('company_requirements', models.TextField()),
                ('remeet', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
